### ISSUE TITLE
Can not get file to compile 

### ISSUE THREAD

**Issue by dodgedoc** [CMendy/MarlinForBTT_SKR-Mini_E3_V2#3]
I am back at a different computer but does the same thing. Here are some pics.
![VSC failure 1](https://user-images.githubusercontent.com/70383473/91639539-ed356d80-e9dc-11ea-9459-14e686bcd2f6.jpeg)
![VSC failure 2](https://user-images.githubusercontent.com/70383473/91639541-f6263f00-e9dc-11ea-8ba8-722d04d72f13.jpeg)

Thanks Barry

**Comment by CMendy** [comment]
Are you double  clicking the build button ? I have notices platform IO lets you do that and run the build twice.

I am on mac  so i don't see this error, but it says there is a file that already exists in the build folder, try deleting the .\.pio\build folder.

**Comment by CMendy** [comment]
I think you could also run the "Clean" task to clear out the build folder.

**Comment by dodgedoc** [comment]
Platform io is looking for this file and can't find it.  Filenotfounderror  No such file or directory 

MarlinForBTT_SKR-Mini_E3_V2-bugfix-2.0.x\\.pio\\libdeps\\STM32F103RC_btt_512K\\_tmp_installing-gbn3rqs3-package\\.\\docs\\class_t_m_c2130_stepper_adde2041047c82600f5e01f52118f92a0_cgraph_org.svg':

**Comment by dodgedoc** [comment]
I am lost on this. Wish we could get code for a board that works form the manufacture..   This sucks..

**Comment by CMendy** [comment]
Don't fret bud, I made a firmware release just for you:
https://github.com/CMendy/MarlinForBTT_SKR-Mini_E3_V2/releases/tag/latest

Use at your own risk tho, I am not responsible if your printer crashes and  burns your house down!

**Comment by CMendy** [comment]
Its based on my last commit, I also updated this repo to pull in the latest Marlin bug fixes, but I haven't tested any of it.
I also built this firmware on my windows machine, and had no issues. I am using VScode and PlatfromIo. i deleted the .pio folder just to make sure, and it downloaded all the libraries it needed and built just fine. so i dont know why you are getting the errors above. something with your set up.

**Comment by dodgedoc** [comment]
Another ? When you import a new file under platformIO and you chose a board, Does it show up with the BTT skr mini e3 v2.0 or what you type in for board. Either way BTT or stm32f103rc_BTT_512K do not show up at all under board list. 
Is this possible the issue? If so where do i download the board i need for platformIO?
Barry

**Comment by CMendy** [comment]
i followed these directions:
https://marlinfw.org/docs/basics/install_platformio_vscode.html

But i do not use the  "Auto Build Marlin" plugin, i have never tried it.

And in your case if you pull this git repo, you do not have to select the default environment. i have already done that here.

So per these directions, install VSCode, install the PlatformIO plugin, then open this repos content in VS code and click on Build. that should be everything. done select any platforms or make any other changes.

**Comment by dodgedoc** [comment]
I did get your firmware to compile. I had to upgrade platformIO core to get it to work. compiled great. I changed what i wanted to and got it to work. Thanks for the help. 
So what is the platformIO core?
Barry

**Comment by CMendy** [comment]
https://docs.platformio.org/en/latest/core/ that's all i know about it. I am closing this issue !
